network : wright.freenode.net
port : 6667
nick : brobot

channels:
    hydratestchannel:
        key: ''
        autojoin: True
defaultgroup : user
groups:
    user:
        inherits_from: None             #Establish hierarchy
        commands:                       #Command List
          - rainbow
          - swedish
          - beaker
    moderator:
        inherits_from: user             #Establish hierarchy
        commands:                       #Command List
          - reload
    admin:
        inherits_from: moderator        #Establish hierarchy
        commands:                       #Command List
          - opme
          - kick
          - promote
    creator:
        inherits_from: admin            #Establish hierarchy
        commands:                       #No extra needed
          - '*'                         #First position * unlocks all commands
users:
    bpurgaso:
        group: creator
commands:
    rainbow:                            #Command Name
        type: external                  #External command, execute with subproc
        encapsulate: True               #Sanitize and surround params in quotes
        timeout: 0                      #No timeout
    swedish:
        type: external
        encapsulate: True
        timeout: 0
    beaker:
        type: external
        encapsulate: True
        timeout: 0
    tune:
        type: external
        encapsulate: False              #Sanitize input, do not put in quotes
        timeout: 60                     #After 60 seconds abort and warn user
    opme:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
    promote:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
    reload:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
    set:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
    kick:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0

