network : wright.freenode.net
port : 6667
nick : brobot
msg_delay : 0.2
channels:
    hydratestchannel:
        key: ''
        autojoin: True
defaultgroup : user
groups:
    user:
        inherits_from: None             #Establish hierarchy
        commands:                       #Command List
          - help
          - rainbow
          - swedish
          - beaker
    moderator:
        inherits_from: user             #Establish hierarchy
        commands:                       #Command List
          - reload
    admin:
        inherits_from: moderator        #Establish hierarchy
        commands:                       #Command List
          - opme
          - kick
          - promote
    creator:
        inherits_from: admin            #Establish hierarchy
        commands:                       #No extra needed
          - '*'                         #First position * unlocks all commands
users:
    bpurgaso:
        group: creator
commands:
    rainbow:                            #Command Name
        type: external                  #External command, execute with subproc
        encapsulate: True               #Sanitize and surround params in quotes
        timeout: 5                      #Minimal Timeout for external command
        help: Colorfies Text!
    swedish:
        type: external
        encapsulate: True
        timeout: 5
        help: Speak like the swedish chef!
    beaker:
        type: external
        encapsulate: True
        timeout: 5
        help: Speak like beaker!
    opme:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
        help: Request OP status from brobot.
    promote:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
        help: Unimplemented
    reload:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
        help: Reloads the global configs
    kick:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
        help: Kick a user or users from the channel!
    help:
        type: internal                  #Internal command, used for perms check
        encapsulate: False
        timeout: 0
        help: Kick a user or users from the channel!

